pipeline {
    agent any

    parameters {
        string(defaultValue: "TEST", description: "What is the deployment name?", name: "deploymentName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2A", "EU-WEST-2A"], description: "Which AZ to deploy to", name: "deployAZ")
        booleanParam(defaultValue: false, description: "Proceed to deploy?", name: "confirmDeployment")
    }

    stages {
        stage("Demo") {
            steps {
                echo "Deployment name is: ${params.deploymentName}"
                echo "Recources will be deployed to: ${params.deployAZ}"
                echo "Deployment has been confirmed?: ${params.confirmDeployment}"
            }
        }
    }
}